### ISSUE TITLE
loss=0 in mip-nerf-360

### ISSUE THREAD

**Issue by Tausc** [Enigmatisms/NeRF#12]
Your working is great! Thank you for the helpful project!
But I got some problems when using the mip-nerf-360 code you provided. When I run mip_train.py, some issues were found.
First, when reading data, an error was generated at the following location:
```
File "mip_train.py", line 353, in <module>
    main()
  File "mip_train.py", line 206, in main
    for i, (train_img, train_tf, ext_img, ext_tf) in enumerate(train_loader):
ValueError: not enough values to unpack (expected 4, got 2)
```

So I deleted **ext_img**, **ext_tf** these two variables, convert the code from:
```
for i, (train_img, train_tf, ext_img, ext_tf) in enumerate(train_loader):
    train_timer.tic()
    train_img = train_img.cuda().squeeze(0)
    train_tf = train_tf.cuda().squeeze(0)
    ext_img = ext_img.cuda().squeeze(0)
    ext_tf = ext_tf.cuda().squeeze(0)
    now_crop = (center_crop if train_cnt < center_crop_iter else 1.)
    valid_pixels, valid_coords = randomFromOneImage(train_img, now_crop)
    ext_valid_pixels, ext_valid_coords = randomFromOneImage(ext_img, now_crop)
    # sample one more t to form (coarse_sample_pnum) proposal interval
    coarse_samples, coarse_lengths, rgb_targets, coarse_cam_rays = validSampler(
        valid_pixels, valid_coords, train_tf, sample_ray_num, coarse_sample_pnum,
        400, 400, train_focal, near_t, far_t, True
    )
    ext_coarse_lengths, ext_rgb_targets, ext_coarse_cam_rays = validSampler(
        ext_valid_pixels, ext_valid_coords, ext_tf, args.N_entropy, coarse_sample_pnum + 1, 400, 400, train_focal, near_t, far_t, False
    )
    coarse_lengths = torch.cat([coarse_lengths, ext_coarse_lengths], 0)
    rgb_targets = torch.cat([rgb_targets, ext_rgb_targets], 0)
            coarse_cam_rays = torch.cat([coarse_cam_rays, ext_coarse_cam_rays], 0)
```

to:
```
for i, (train_img, train_tf) in enumerate(train_loader):
    train_timer.tic()
    train_img = train_img.cuda().squeeze(0)
    train_tf = train_tf.cuda().squeeze(0)
    now_crop = (center_crop if train_cnt < center_crop_iter else 1.)
    valid_pixels, valid_coords = randomFromOneImage(train_img, now_crop)

    # sample one more t to form (coarse_sample_pnum) proposal interval
    coarse_samples, coarse_lengths, rgb_targets, coarse_cam_rays = validSampler(
        valid_pixels, valid_coords, train_tf, sample_ray_num, coarse_sample_pnum, 
        400, 400, train_focal, near_t, far_t, True
    )
```

I learned from the code that ext_img, ext_tf is randomly selected. What is the purpose of selecting these two data? Is it safe to directly delete theses two variables? 
But at least the code can successfully run through, so I started training the model. The initial loss is:
![image](https://github.com/Enigmatisms/NeRF/assets/50770432/e4736984-01df-48fb-8430-aba75a9ab098)

But after a few batches, prop_loss and entropy_ ray_zvals_loss begins to steadily output 0:
![image](https://github.com/Enigmatisms/NeRF/assets/50770432/5f9601e6-5944-45a5-8be4-d9cb3a4f048b)
May I ask why this situation is happening? The dataset I am using is 'lego' in theofficial dataset nerf_synthetic. How can I solve the problem?

**Comment by Enigmatisms** [comment]
I'll take a look tonight. This repo is old and I added magical things in the code in June...

**Comment by Enigmatisms** [comment]
Can you post the commit id for your current clone? It seems that `mip_train.py` was deprecated a long time ago. I have been unable to find the code snippet posted by you.

**Comment by Tausc** [comment]
```
commit 0f4488afd9d17b7cab58e7c03438e603cbff2eb1 (HEAD -> infonerf, origin/infonerf)
Merge: f510510 85fd412
Author: Qianyue He <46109954+Enigmatisms@users.noreply.github.com>
Date:   Wed Jun 22 18:08:09 2022 +0800

    Merge pull request #3 from Dinngger/infonerf

    infonerf
```

**Comment by Enigmatisms** [comment]
I got it. The `infonerf` branch is not implemented by me so I made a mistake in merging the PR. In line 182:
```python
trainset = CustomDataSet("../dataset/nerf_synthetic/%s/"%(dataset_name), transform_funcs, True, use_alpha = False)
testset = CustomDataSet("../dataset/nerf_synthetic/%s/"%(dataset_name), transform_funcs, False, use_alpha = False)
```
This should have been `CustomDataSet2` implemented in `py/dataset.py`. So just replacing `CustomDataSet` with `CustomDataSet2` should do. This branch incorporated info-NeRF so if the perturbed (augmented) poses are not generated, it will be sure that we will have zero loss.

Also note that:
- MipNeRF 360 implementation is incomplete, the support for the unbounded scene (frustum contraction) is not implemented.
- This branch is deprecated and not recommended to be used.

**Comment by Tausc** [comment]
Thank you for replying! I have read `CustomiDataSet2` before, but I have found that `ext_img`, `ext_tf` are randomly selected. I wonder why you do this?

**Comment by Enigmatisms** [comment]
The code makes no sense to me actually. We are to sample unseen views but `ext_tf` is clearly from a seen view with available supervision. Actually, the implementation should be:
- Acquiring ray direction from one image using the camera intrinsics and extrinsics. In this step we only need `CustomiDataSet`
- **Perturb** the ray direction to create more ray directions (data-augmentaion).
- Apply ray entropy loss. The perturbed rays does not have gt and the entropy loss does not need gt.
The above procedures can be found in my repo [nerfstudio-giga/ray_generator.py, line 82, class PerturbRayGenerator](https://github.com/Enigmatisms/nerfstudio-giga/blob/main/nerfstudio/model_components/ray_generators.py). I add Info-NeRF ray sampler in the nerfstudio and I think this makes more sense for actually generating unseen view rays.

To me, implementing another random sampling for the same dataset is meaningless and you don't have to pay much attention to it. @Dinngger care to have a little explanation for why this is?

**Comment by Dinngger** [comment]
Refer to the official implementation of Info-NeRF:
https://github.com/mjmjeong/InfoNeRF/blob/main/utils/generate_near_c2w.py

**Comment by Enigmatisms** [comment]
So this is actually perturbing the ray direction using zero-mean gaussian random floats:
```python
 def random_pos(self, c2w):     
        c2w[:, -1:] += self.near_c2w_trans*torch.randn(3).unsqueeze(-1)
        return c2w 
```
So..., why should we randomly sample the images again in the `CustomiDataSet2`? @Dinngger

**Comment by Dinngger** [comment]
Because you didn't know how to randomly sample ray directions at the time, you wrote a simple version.

**Comment by Enigmatisms** [comment]
Did I? I thought the code was implemented by you since this was your homework.

**Comment by Tausc** [comment]
OK now I got it. We speculate the reason that loss related to the mip changed to 0 rapidly may be the `prop_loss `is too large  compared to `rgb_loss` and `dist_loss`. But since this branch is not recommended to be used, we will try some other methods. Thank you very much!!
