### ISSUE TITLE
Can you provide codes of Cuda ?

### ISSUE THREAD

**Issue by ZZy129326999** [Enigmatisms/NeRF#4]
Hello expert! I VERY want to study cuda codes, can you provide codes of cuda?? Thank you very much!

**Comment by Enigmatisms** [comment]
Of course. You could roll back to commit `cb4c4ec57098e718ab238cfc06ece2e28335c852`. In that commit, a folder named `cuda/` can be found in the root directory, including all the files such as `setup.py` and the source code you need. To compile the code (correctly), plz refer to `README.md`.

btw, resulting from some unclear bugs (might be that I didn't concat the original input to positional encodings), this commit failed to reproduce the results of the original paper, therefore the later versions of this repo abandoned CUDA implementation. Also, CUDA implementation is limitted to the following modules: 1. positional encoding; 2. image sampler; 3. inverse transform sampler; these CUDA implemented modules are all unit-tested, which should produce correct results, but they're not optimized therefore they might not be elegant or correct, plz be careful.

**Comment by ZZy129326999** [comment]
Thank you very much!!!
