### ISSUE TITLE
Cannot find reference 'encoding' in 'nerf_helper'.py'. 

### ISSUE THREAD

**Issue by ZZy129326999** [Enigmatisms/NeRF#6]
Dear export, hello! I want to learn about the details of "Cannot find reference 'encoding' in 'nerf_helper'.py'. ". I saw the description of pybind11 from CUDA EXTENSION. But there is a reference information **"Cannot find reference 'encoding' in 'nerf_helper'.py'. "**  in model.py when running. Thank you very much!
```
model.py
from nerf_helper import encoding

nerf_extension.cu
PYBIND11_MODULE (TORCH_EXTENSION_NAME, nerf_helper)
{
  	nerf_helper.def ("comservativeSampling", &cudaSampler, conservative_sampler_docs.c_str());
  	nerf_helper.def ("sampling", &easySampler, sampler_docs.c_str());
	nerf_helper.def ("encoding", &positionalEncode, pe_docs.c_str());  // This !! Thank you !!!
	nerf_helper.def ("invTransformSample", &inverseTransformSample, inv_tf_docs.c_str());
	nerf_helper.def ("invTransformSamplePt", &inverseTransformSamplePt, inv_tf_pt_docs.c_str());
	nerf_helper.def ("imageSampling", &imageSampler, image_sampler_doc.c_str());
	nerf_helper.def ("validSampling", &validSampler, valid_sampler_doc.c_str());
}
```

**Comment by Enigmatisms** [comment]
There is no `nerf_helper.py`. `nerf_helper` as you see, is defined by `setup.py` in folder `cuda/` (line 10). The module is called `nerf_helper` and it is already compiled, dynamically linked and loaded by your executable script. Therefore there is no python definition for `encoding`. Function `encoding` is "declared" in python, and defined in CUDA c++ (plz refer to file `cuda/pe.cu`). The definition is **linked** to the name `encoding`. 

So, if python interpreter can not fine `encoding`, it might be (if I got it right):
- You didn't correctly compile pytorch CUDA extension (follow README.md, running setup.py), so the interpreter had no where to find the definition of this function. Solution is to compile CUDA extension correctly (normally, successful compilation will result in `.egg` `.dist`(?maybe) files and it will tell you `Finished ... (I don't remember)` in the terminal).

**Comment by ZZy129326999** [comment]
Thank you dear export!! I could generate nerf_helper.py after running cuda.
`
nerf_helper.py
def __bootstrap__():
    global __bootstrap__, __loader__, __file__
    import sys, pkg_resources, importlib.util
    __file__ = pkg_resources.resource_filename(__name__, 'nerf_helper.cpython-39-x86_64-linux-gnu.so')
    __loader__ = None; del __bootstrap__, __loader__
    spec = importlib.util.spec_from_file_location(__name__,__file__)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
__bootstrap__()
`
Is this not normal? Thank you very much!

**Comment by ZZy129326999** [comment]
![图片](https://user-images.githubusercontent.com/72543018/178792684-3c675332-0964-4770-9f4b-52ffeba6fca0.png)
(9 line) Thank you very much!!!!

**Comment by ZZy129326999** [comment]
I directly run setup.py with your method, I understand that cuda is not used in the project, but I am just curious why the compiled nerf_helper cannot retrieve the encoding.

**Comment by Enigmatisms** [comment]
Well, it works for me even after checking out this older version and recompile:
![Screenshot 2022-07-14 012316](https://user-images.githubusercontent.com/46109954/178793872-bb60c28a-73ab-4daa-9ad5-a2a44d397709.png)
Did you try importing this in a python shell? What does it output?

**Comment by ZZy129326999** [comment]
Yes! Your code will not generate any errors during runtime! They are as good as you are! ! Thank you very much! You are a real export!!!!!

**Comment by Enigmatisms** [comment]
Thank you. That's a little overstating. Hope u can learn the things u want.
